[phases.setup]
nixPkgs = ['python312', 'gcc', 'g++']

[phases.install]
cmds = [
    'pip install uv',
    'uv sync --frozen --no-dev'
]

[start]
cmd = "uvicorn src.main:app --host 0.0.0.0 --port $PORT"